version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379

  backend:
    image: thangloitran/react-news-backend
    environment:
      - REDIS_HOST=redis
    ports:
      - 8000:8000
    depends_on:
      - redis

  frontend:
    image: thangloitran/react-news

    ports:
      - 80:5173
    depends_on:
      - backend